env:
  browser: true
  es6: true
extends:
  - standard
  - react-app
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  no-unused-vars: "off"
  "@typescript-eslint/no-unused-vars": "error"
  import/order:
    - error
    - groups:
        - - builtin
          - internal
        - external
        - parent
        - - index
          - sibling
      newlines-between: always-and-inside-groups
      alphabetize:
        order: asc
        caseInsensitive: true
