env:
  browser: true
  es6: true
extends:
  - standard
  - react-app
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - "@typescript-eslint"
  - simple-import-sort
rules:
  no-unused-vars: "off"
  "@typescript-eslint/no-unused-vars": "error"
  "simple-import-sort/sort": "error"
#  import/order:
#    - warn
#    - groups:
#        - - builtin
#          - internal
#        - external
#        - parent
#        - - index
#          - sibling
#      newlines-between: always-and-inside-groups
#      alphabetize:
#        order: asc
#        caseInsensitive: true
